require('!file-loader?name=[name].[ext]!../static/img/logo-ctl.png');
require('!file-loader?name=[name].[ext]!../static/img/logo-cdm.png');
require('!file-loader?name=[name].[ext]!../static/img/dresser_candies_t.png');
require(
    '!file-loader?name=[name].[ext]!../static/img/dresser_familyphoto_t.png');
require('!file-loader?name=[name].[ext]!../static/img/dresser_dentures_t.png');
require('!file-loader?name=[name].[ext]!../static/img/dresser_gmonitor_t.png');
require(
    '!file-loader?name=[name].[ext]!../static/img/dresser_appointment_t.png');
require(
    '!file-loader?name=[name].[ext]!../static/img/dresser_pillbottles_t.png');
require(
    '!file-loader?name=[name].[ext]!../static/img/dresser_weddingphoto_t.png');
require('!file-loader?name=[name].[ext]!../static/img/dresser_cream_t.png');
require(
    '!file-loader?name=[name].[ext]!../static/img/dresser_medicard_t.png');
require('!file-loader?name=[name].[ext]!../static/img/shim.gif');
require('!file-loader?name=[name].[ext]!../static/img/dresser_print.jpg');
